"""access token

Revision ID: eae268e5ea1a
Revises: 577a3bf88bbd
Create Date: 2024-10-16 16:36:51.274409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae268e5ea1a'
down_revision: Union[str, None] = '577a3bf88bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tokens',
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('access_token'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_tokens', schema='public')
    # ### end Alembic commands ###
